/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pennstateschedule;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author cjd258
 */
public class MainMenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuPanel
     */
    public MainMenuPanel() {
        initComponents();
    } // constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prevScheduleButton = new javax.swing.JButton();
        facPrefButton = new javax.swing.JButton();
        currentClassButton = new javax.swing.JButton();
        currentSchedButton = new javax.swing.JButton();

        prevScheduleButton.setText("View Previous Semesters");
        prevScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevScheduleButtonActionPerformed(evt);
            }
        });

        facPrefButton.setText("View/Edit Faculty Preferences");
        facPrefButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facPrefButtonMouseClicked(evt);
            }
        });
        facPrefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facPrefButtonActionPerformed(evt);
            }
        });

        currentClassButton.setText("View Current Class List");
        currentClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentClassButtonActionPerformed(evt);
            }
        });

        currentSchedButton.setText("View Current Schedule");
        currentSchedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentSchedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prevScheduleButton)
                        .addGap(56, 56, 56)
                        .addComponent(facPrefButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentClassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(currentSchedButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prevScheduleButton)
                    .addComponent(facPrefButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentClassButton)
                    .addComponent(currentSchedButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void facPrefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facPrefButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facPrefButtonActionPerformed

    private void facPrefButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facPrefButtonMouseClicked
        // TODO add your handling code here:
        JFrame facPref;
        try 
        {
            facPref = new FacultyPreferences();
            facPref.setLocationRelativeTo(null);
            facPref.setVisible(true);
            facPref.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        } // try
        catch (SQLException ex) 
        {
            Logger.getLogger(MainMenuPanel.class.getName()).log(Level.SEVERE, null, ex);
        } // catch
    }//GEN-LAST:event_facPrefButtonMouseClicked

    private void prevScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevScheduleButtonActionPerformed
        JFrame prevSched = new PreviousSchedules();
        prevSched.setLocationRelativeTo(null);
        prevSched.setVisible(true);
        prevSched.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_prevScheduleButtonActionPerformed

    private void currentClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentClassButtonActionPerformed
        JFrame classList = new NewClasses();
        classList.setLocationRelativeTo(null);
        classList.setVisible(true);
        classList.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_currentClassButtonActionPerformed

    private void currentSchedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentSchedButtonActionPerformed
        JFrame schedList = new NewSchedule();
        schedList.setLocationRelativeTo(null);
        schedList.setVisible(true);
        schedList.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_currentSchedButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton currentClassButton;
    private javax.swing.JButton currentSchedButton;
    private javax.swing.JButton facPrefButton;
    private javax.swing.JButton prevScheduleButton;
    // End of variables declaration//GEN-END:variables
} // MainMenuPanel
